import { Product } from '@/types/marketing';

export const PRODUCTS: Product[] = [
  {
    id: 'business-nfc-card',
    name: 'Business NFC Card',
    price: 499,
    originalPrice: 599,
    rating: 5.0,
    reviewsCount: 126,
    category: 'NFC Card',
    image: '/images/MainImg/business-nfc-card.webp',
    images: [
      '/images/MainImg/business-nfc-card.webp',
      '/images/MarketingImg/business-nfc-card-marketing-1.webp',
      '/images/MarketingImg/business-nfc-card-marketing-2.webp',
      '/images/MarketingImg/business-nfc-card-marketing-3.webp',
    ],
    badge: 'BEST SELLER',
    tagline: 'All-in-one digital business card with dynamic profile control.',
    description:
      'The classic executive NFC card that instantly shares your entire profile with one tap.',
    highlights: ['NFC + QR Hybrid', 'Lead Capture & Analytics', 'Lifetime Validity'],
    features: [
      'Tap-to-Connect',
      'Dynamic Profile Control',
      'Multi-Link & Portfolio Hub',
      'Custom Metal / Wooden / Eco-Friendly Designs',
      'Lead Capture & Analytics',
      'Direct Appointment Scheduling',
      'NFC + QR Code Hybrid Combo',
      'Custom Action Button (Call-to-Action)',
      'Eco-Friendly & One-Time Investment',
      'AI Networking & Auto-Follow-up',
      'Google Review Automation',
      'Lifetime Validity',
    ],
  },
  {
    id: 'premium-nfc-card',
    name: 'Premium NFC Card',
    price: 699,
    originalPrice: 799,
    rating: 5.0,
    reviewsCount: 118,
    category: 'NFC Card',
    image: '/images/MainImg/premium-nfc-card.webp',
    images: [
      '/images/MainImg/premium-nfc-card.webp',
      '/images/MarketingImg/premium-nfc-card-marketing-1.webp',
      '/images/MarketingImg/premium-nfc-card-marketing-2.webp',
      '/images/MarketingImg/premium-nfc-card-marketing-3.webp',
    ],
    badge: 'NEW ARRIVAL',
    tagline: 'Premium build with a full dynamic dashboard and instant contact sync.',
    description:
      'Our most feature-rich NFC card, wrapped in a premium material build with a complete digital dashboard.',
    highlights: ['Premium Material', 'Dynamic Dashboard', 'Lifetime Validity'],
    features: [
      'Premium Material Build',
      'Eco-Friendly Sustainability',
      'Dynamic Dashboard',
      'NFC + QR Hybrid Combo',
      'Instant Contact Sync',
      'Lead Capture Form',
      'Multi-Profile Switching',
      'Appointment Booking',
      'Direct Google Review AI Link',
      'Custom CTA Buttons',
      'Lifetime Validity',
    ],
  },
  {
    id: 'insta-card',
    name: 'Insta Card',
    price: 499,
    originalPrice: 599,
    rating: 5.0,
    reviewsCount: 104,
    category: 'NFC Card',
    image: '/images/MainImg/insta-card.webp',
    images: [
      '/images/MainImg/insta-card.webp',
      '/images/MarketingImg/insta-card-marketing-1.webp',
      '/images/MarketingImg/insta-card-marketing-2.webp',
      '/images/MarketingImg/insta-card-marketing-3.webp',
    ],
    tagline: 'Grow your Instagram in one tap — followers, reels, DM & more.',
    description:
      'The Instagram-themed NFC card that turns every handshake into a new follower.',
    highlights: ['1-Tap Instagram Follow', 'Zero App Download', 'Real-time Follower Counter'],
    features: [
      '1-Tap Instagram Follow',
      'Instant Reel & Post Showcase',
      // 'Auto-Follow-up Message',
      // 'Direct DM Link',
      // 'Instagram Store/Shop Direct Access',
      'Multiple Account Switcher',
      'Custom Instagram QR Combo',
      'Lead Generation via DM',
      // 'Real-time Follower Counter Integration',
      'Custom Instagram-Themed Material',
      'Zero App Download Needed',
    ],
  },
  {
    id: 'google-review-card',
    name: 'Google Review Card',
    price: 499,
    originalPrice: 599,
    rating: 5.0,
    reviewsCount: 97,
    category: 'NFC Card',
    image: '/images/MainImg/google-review-card.webp',
    images: [
      '/images/MainImg/google-review-card.webp',
      '/images/MarketingImg/google-review-card-marketing-1.webp',
      '/images/MarketingImg/google-review-card-marketing-2.webp',
      '/images/MarketingImg/google-review-card-marketing-3.webp',
    ],
    tagline: 'Turn every customer visit into a fresh Google review.',
    description:
      'A dedicated NFC card engineered to funnel happy customers straight to your Google reviews.',
    highlights: ['Direct Review Redirection', 'Smart Gatekeeping', 'GMB SEO Boost'],
    features: [
      'Direct Review Redirection',
      // 'Negative Feedback Filter (Smart Gatekeeping)',
      // 'Auto-Prompt for Photo Upload',
      'Custom Business Logo Printing',
      'Zero App Download Required',
      'Review-to-Discount Automation',
      'Dynamic Link Control',
      'Multi-Language Prompt Support',
      'Pre-written AI Review Suggestions',
      // 'One-Time Purchase & Lifetime Use',
      'Water & Scratch Resistant',
      'Google My Business (GMB) SEO Boost',
      // 'Instant WhatsApp Thank You Automation',
      'High-Grade Chip Technology',
    ],
  },
  {
    id: 'linkedin-card',
    name: 'LinkedIn Card',
    price: 399,
    originalPrice: 499,
    rating: 5.0,
    reviewsCount: 132,
    category: 'NFC Card',
    image: '/images/MainImg/linkedin-card.webp',
    images: [
      '/images/MainImg/linkedin-card.webp',
      '/images/MarketingImg/linkedin-card-marketing-1.webp',
      '/images/MarketingImg/linkedin-card-marketing-2.webp',
      '/images/MarketingImg/linkedin-card-marketing-3.webp',
    ],
    tagline: 'Make a professional first impression with a one-tap LinkedIn card.',
    description:
      'An elegant matte-black LinkedIn NFC card that opens your profile, resume and portfolio instantly.',
    highlights: ['1-Tap Profile Connection', 'Digital Resume', 'Corporate Badge'],
    features: [
      '1-Tap Profile Connection',
      // 'Digital Resume & CV Viewer',
      'Direct QR Code Backup',
      'Featured Posts & Articles Showcase',
      'Direct InMail / Message Button',
      'Company Page Integration',
      'Custom Metal & Matte Black Design',
      'Multi-Language Bio Support',
      'Event & Webinar Registration',
      'Auto-Save to Phone Contacts (.vcf)',
      'NFC Embedded Corporate Badges',
      'Portfolio Video Showcase',
      'Zero App Installation Needed',
    ],
  },
  {
    id: 'facebook-card',
    name: 'Facebook Card',
    price: 399,
    originalPrice: 499,
    rating: 5.0,
    reviewsCount: 88,
    category: 'NFC Card',
    image: '/images/MainImg/facebook-card.webp',
    images: [
      '/images/MainImg/facebook-card.webp',
      '/images/MarketingImg/facebook-card-marketing-1.webp',
      '/images/MarketingImg/facebook-card-marketing-2.webp',
      '/images/MarketingImg/facebook-card-marketing-3.webp',
    ],
    tagline: 'One tap to your page, Messenger, reels & shop.',
    description:
      'A custom Facebook-blue NFC card that connects you to your page, Messenger and shop in one tap.',
    highlights: ['1-Tap Page & Profile', 'Messenger Auto-Chat', 'Password Protected Content'],
    features: [
      '1-Tap Profile & Page Open',
      'Direct Friend Request / Follow Button',
      'Facebook Messenger Auto-Chat Launch',
      'Instant Page Review & Rating',
      'Dynamic Profile Control',
      'Facebook Reels & Video Showcase',
      'Dual NFC + Custom QR Backup',
      'Facebook Shop & Product Catalog Direct Access',
      'Facebook Group Join Shortcut',
      'Multi-Profile Landing Page',
      'Custom Facebook Blue Design',
      'Password Protected Private Content',
      'Zero App Installation',
    ],
  },
  {
    id: 'metal-nfc-card',
    name: 'Metal NFC Card',
    price: 1499,
    originalPrice: 1999,
    rating: 4.9,
    reviewsCount: 64,
    category: 'NFC Card',
    image: '/images/MainImg/metal-nfc-card.webp',
    images: ['/images/MainImg/metal-nfc-card.webp'],
    badge: 'NEW ARRIVAL',
    tagline: 'A heavyweight luxury card in stainless steel, built to last forever.',
    description:
      'Precision laser-engraved stainless steel with a matte finish — the ultimate statement of success.',
    highlights: ['Stainless Steel', 'Precision Laser Engraving', 'Lifetime Validity'],
    features: [
      'Stainless Steel & Matte Finish',
      'Precision Laser Engraving',
      'Heavyweight Luxury Feel',
      'Unbreakable & Scratch-Resistant',
      'Hybrid Metal + PVC Shield Technology',
      'Instant 1-Tap Contact Save (.vcf)',
      'Dynamic Dashboard',
      'Multi-Link Digital Hub',
      'NFC + Laser QR Combo',
      'Zero App Download Required',
      'Digital Catalogue & Portfolio Showcase',
      'Direct Social Media Redirection',
      'Auto WhatsApp Follow-Up Launch',
      'Multi-Profile Switcher',
      'Tap Analytics Track',
      'Eco-Friendly Lifetime Investment',
      'Lifetime Validity (No Subscription)',
    ],
  },
  {
    id: 'wooden-nfc-card',
    name: 'Wooden NFC Card',
    price: 1299,
    originalPrice: 1699,
    rating: 4.9,
    reviewsCount: 57,
    category: 'NFC Card',
    image: '/images/MainImg/wooden-nfc-card-1.webp',
    images: [
      '/images/MainImg/wooden-nfc-card-1.webp',
      '/images/MainImg/wooden-nfc-card-2.webp',
      '/images/MainImg/wooden-nfc-card-3.webp',
      '/images/MainImg/wooden-nfc-card-4.webp',
    ],
    badge: 'NEW ARRIVAL',
    tagline: 'Handcrafted natural wood with a zero-plastic, paperless footprint.',
    description:
      '100% real natural wood with a unique grain pattern — sustainable networking in your pocket.',
    highlights: ['100% Real Wood', 'Eco-Friendly', 'Go-Green Campaign'],
    features: [
      '100% Real Natural Wood',
      'Unique Wood Grain Pattern',
      'Eco-Friendly Sustainability',
      'Precision Laser Engraving',
      'Lightweight & Durable Build',
      'Instant 1-Tap Contact Save (.vcf)',
      'Dynamic Dashboard',
      'Multi-Link Digital Profile',
      'NFC + Laser QR Combo',
      'Zero App Download Required',
      'Lead Capture Form Integration',
      'Digital Menu & Portfolio Showcase',
      'Direct Social Media Redirection',
      'Multi-Profile Switcher',
      'Tap Analytics Track',
      'Paperless Go-Green Campaign',
      'Lifetime Validity (No Subscription)',
    ],
  },
  {
    id: 'combo-1-card-standee',
    name: 'Combo 1 - Business NFC Card + NFC Standee',
    price: 1199,
    rating: 5.0,
    reviewsCount: 42,
    category: 'NFC Card',
    image: '/images/MainImg/combo-nfc-card-nfc-standee.webp',
    images: [
      '/images/MainImg/combo-nfc-card-nfc-standee.webp',
    ],
    tagline:
      'Business NFC Card + NFC Standee — a complete NFC + QR solution for personal networking, business visibility, location sharing, reviews and unified analytics.',
    description:
      'Business NFC Card + NFC Standee — a complete NFC + QR solution for personal networking, business visibility, location sharing, reviews and unified analytics.',
    highlights: ['Dual NFC + QR Tech', 'One-Time Investment & Lifetime Validity'],
    features: [
      'Matching Luxury Branding',
      'Personal + Location Mobility',
      'Dual NFC + QR Tech',
      'Waterproof & Scratch-Proof',
      'Ergonomic Counter Standee',
      'Centralized Dynamic Dashboard',
      '1-Tap Contact Save (.vcf)',
      'Smart Profile Routing',
      'Digital Catalogue & Portfolio Viewer',
      'Direct Social Media Integration',
      'Smart Review Filter Gatekeeping',
      'Review Capture',
      'Unified Tap Analytics',
      'Zero App Download Required',
      'One-Time Investment & Lifetime Validity',
    ],
  },
  {
    id: 'google-review-standee',
    name: 'Google Review Standee',
    price: 599,
    originalPrice: 699,
    rating: 5.0,
    reviewsCount: 142,
    category: 'Standee NFC',
    image: '/images/MainImg/google-review-standee.webp',
    images: [
      '/images/MainImg/google-review-standee.webp',
      '/images/MarketingImg/google-review-standee-marketing-1.webp',
      '/images/MarketingImg/google-review-standee-marketing-2.webp',
      '/images/MarketingImg/google-review-standee-marketing-3.webp',
    ],
    badge: 'BEST SELLER',
    tagline: 'Counter-top standee that turns tables & counters into 5-star generators.',
    description:
      'A 3D wooden & metallic standee that collects glowing Google reviews with a single tap.',
    highlights: ['Dual Tap & Scan', 'Smart Rating Filter', 'GMB Ranking Boost'],
    features: [
      '3D Wooden & Metallic Look',
      'Dual Tap & Scan (NFC + Large QR)',
      'Table & Counter Ergonomics',
      'Waterproof & Scratch-Proof Coating',
      'Custom Brand Logo & Color Theme',
      'Instant Review Redirection (1-Tap)',
      'Smart Rating Filter (Negative Review Gate)',
      'Pre-Written AI Review Suggestions',
      'Local SEO Boost (GMB Ranking)',
      'Dynamic Link Control (Zero Reprinting)',
      'Clear "Tap Here" Visual Indicator',
      'Zero App Download',
      'Multi-Language Review Support',
      'One-Time Investment & Lifetime Validity',
    ],
  },
  {
    id: 'business-profile-standee',
    name: 'Business Profile Standee',
    price: 599,
    originalPrice: 699,
    rating: 5.0,
    reviewsCount: 91,
    category: 'Standee NFC',
    image: '/images/MainImg/business-profile-standee.webp',
    images: [
      '/images/MainImg/business-profile-standee.webp',
      '/images/MarketingImg/business-profile-standee-marketing-1.webp',
      '/images/MarketingImg/business-profile-standee-marketing-2.webp',
      '/images/MarketingImg/business-profile-standee-marketing-3.webp',
    ],
    tagline: 'Your entire business profile, one tap away on every counter.',
    description:
      'A premium wooden & metal standee that shares your full business profile, reviews and direction.',
    highlights: ['All-in-One Profile', 'Location & Map', 'Multi-Link Hub'],
    features: [
      '3D Premium Wooden & Metal Stand',
      'Dual Tap & Scan (NFC + Large QR)',
      'Waterproof & UV Scratch-Resistant',
      'Ergonomic Counter Angle',
      'Clear Visual "Tap Here" Indicator',
      'All-in-One Business Landing Page',
      'Instant Contact Save (.vcf)',
      'Google Map & Location Direction',
      'Smart Review & Feedback Gate',
      'Direct WhatsApp Chat Launcher',
      'Social Media Multi-Link Hub',
      'Lead Capture Form',
      'Dynamic Control (Zero Reprinting)',
      'Zero App Download Required',
      'Multi-Language Support',
      'One-Time Investment & Lifetime Use',
    ],
  },
  {
    id: 'all-in-one-standee-3',
    name: 'All In One Standee (3 Profile)',
    price: 799,
    originalPrice: 999,
    rating: 5.0,
    reviewsCount: 73,
    category: 'Standee NFC',
    image: '/images/MainImg/all-in-one-standee-3-profile.webp',
    images: [
      '/images/MainImg/all-in-one-standee-3-profile.webp',
      '/images/MarketingImg/all-in-one-standee-3-profile-marketing-1.webp',
      '/images/MarketingImg/all-in-one-standee-3-profile-marketing-2.webp',
      '/images/MarketingImg/all-in-one-standee-3-profile-marketing-3.webp',
      '/images/MarketingImg/all-in-one-standee-3-profile-marketing-4.webp',
    ],
    badge: 'NEW ARRIVAL',
    tagline: 'Triple NFC chip — review, follow & chat from one premium standee.',
    description:
      'Three distinct tap zones in a single 3D standee — review, follow and chat in one glance.',
    highlights: ['3-in-1 NFC Chip', 'Triple QR Backup', 'Smart Review Gate'],
    features: [
      '3-in-1 Triple NFC Chip Integration',
      'Distinct Visual Tap Zones',
      '3D Premium Wooden & Metallic Finish',
      'Triple QR Code Backup',
      'Waterproof & UV Scratch-Proof',
      'Customizable 3 Profiles',
      'Instant Profile Switcher',
      '1-Tap Review + Follow + Chat',
      'Zero App Download Required',
      'Ergonomic Counter Angle',
      'Smart Review Filter Gatekeeping',
      'Pre-Written AI Review Suggestions',
      'Dynamic Dashboard Control',
      'Multi-Language Support',
      'One-Time Investment & Lifetime Use',
    ],
  },
  {
    id: 'all-in-one-standee-4',
    name: 'All In One Standee (4 Profile)',
    price: 899,
    originalPrice: 1099,
    rating: 5.0,
    reviewsCount: 49,
    category: 'Standee NFC',
    image: '/images/MainImg/all-in-one-standee-4-profile.webp',
    images: [
      '/images/MainImg/all-in-one-standee-4-profile.webp',
      '/images/MarketingImg/all-in-one-standee-4-profile-marketing-1.webp',
      '/images/MarketingImg/all-in-one-standee-4-profile-marketing-2.webp',
      '/images/MarketingImg/all-in-one-standee-4-profile-marketing-3.webp',
      '/images/MarketingImg/all-in-one-standee-4-profile-marketing-4.webp',
    ],
    tagline: 'Four profiles in one — the ultimate multi-action counter standee.',
    description:
      'Quad-NFC integration with a 4-zone visual layout for maximum networking impact.',
    highlights: ['Quad NFC Chip', '4-Zone Layout', 'Multi-Action Launcher'],
    features: [
      'Quad-NFC Chip Integration',
      '4-Zone Distinct Visual Layout',
      '3D Premium Acrylic & Metal Finish',
      'Quad QR Code Backup',
      'Waterproof & UV Scratch-Proof',
      'Customizable Any 4 Profiles',
      'Instant Multi-Action Launcher',
      'Zero App Download Required',
      'Ergonomics & Viewing Angle',
      'Smart Rating Filter Gatekeeping',
      'Pre-Written AI Review Suggestions',
      'Dynamic Dashboard Control',
      'Multi-Language Support',
      'One-Time Investment & Lifetime Use',
    ],
  },
  {
    id: 'google-review-nfc-plate',
    name: 'Google Review NFC Plate',
    price: 699,
    originalPrice: 899,
    rating: 5.0,
    reviewsCount: 38,
    category: 'Plate NFC',
    image: '/images/MainImg/google-review-nfc-plate.webp',
    images: ['/images/MainImg/google-review-nfc-plate.webp'],
    badge: 'NEW ARRIVAL',
    tagline: 'Wall or counter-mount review plate with acrylic mirror finish.',
    description:
      'A premium acrylic review plate that collects Google reviews everywhere your customers are.',
    highlights: ['Wall & Counter Mount', 'Acrylic Mirror Finish', 'Smart Rating Filter'],
    features: [
      'Wall & Counter Mountable Design',
      'Premium Acrylic & Mirror Finish',
      'Strong 3M Self-Adhesive Backing',
      'Waterproof & UV Protection',
      'High-Contrast Google Branding & Logo',
      'Instant Review Redirection (1-Tap)',
      'Dual NFC + Large QR Backup',
      'Smart Rating Filter (Negative Review Gate)',
      'Pre-Written AI Review Suggestions',
      'Local Google SEO Boost',
      'Real-Time Analytics Dashboard',
      'Dynamic Link Control',
      'Multi-Location Redirection',
      'Clear Visual "Tap Here" Indicator',
      'Zero App Installation Needed',
      'Anti-Tamper & Scratch Resistant',
      'Multi-Language Support',
      'One-Time Investment & Lifetime Validity',
    ],
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'NFC Card', label: 'NFC Card' },
  { id: 'Standee NFC', label: 'Standee NFC' },
  { id: 'Plate NFC', label: 'Plate NFC' },
  { id: 'Combo', label: 'Combo' },
] as const;